# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2022-18.04

    steps:
    # Checks-out repo to $GITHUB_WROKSPACE
    - uses: actions/checkout@v2
    
    - name: Grant execute permission for graldew
      run: chmod +x gradlew
    
    - name: Compile and run tests
      run: ./gradlew build
